"""
Django settings for lend project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

from django.core.urlresolvers import reverse_lazy
from decouple import config
from dj_database_url import parse
from sys import path
from unipath import Path
import os

BASE_DIR = Path(__file__).absolute().ancestor(1)
path.insert(0, os.path.join(BASE_DIR, 'apps'))

PROJECT_NAME = config('PROJECT_NAME', default='lend')
SECRET_KEY = config('SECRET_KEY', default='debug')
DEBUG = config('DEBUG', default=True)

ALLOWED_HOSTS = []

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

LOCAL_APPS = [
    'core',
    'client'
]

THIRD_APPS = [
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS + THIRD_APPS

SITE_ID = 1

LOGIN_REDIRECT_URL = reverse_lazy('index')
LOGIN_URL = reverse_lazy('index')

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lend.urls'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['lend/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lend.wsgi.application'

DATABASES = {
    'default': config(
        'DATABASE_URL', default='sqlite:///{0}/{1}'.format(
            BASE_DIR.child('db'), 'alpha.sqlite3'
        ), cast=parse),
}

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_ROOT = config('STATIC_ROOT', default=BASE_DIR.child('staticfiles'))

STATIC_URL = config('STATIC_URL', default='/static/')

STATICFILES_DIRS = (
    BASE_DIR.child('static'),
    BASE_DIR.child('static').child('bower_components')
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'djangobower.finders.BowerFinder'
)
